---- Base app schema

-- -- Org
-- CREATE TABLE "org" (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
--   name varchar(128) NOT NULL UNIQUE,

--   -- Timestamps
--   cid bigint NOT NULL,
--   ctime timestamp with time zone NOT NULL,
--   mid bigint NOT NULL,
--   mtime timestamp with time zone NOT NULL
-- );

-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User', 'UnVarifiedUser');

CREATE TABLE "users" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  user_id varchar(30) NOT NULL UNIQUE,
  email varchar(256) NOT NULL UNIQUE,
  name varchar(128) NOT NULL,
  typ user_typ NOT NULL DEFAULT 'UnVarifiedUser',

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);

CREATE TABLE "auth" (
  user_serial_id BIGINT PRIMARY KEY,

  -- Auth
  pwd varchar(256) NOT NULL,
  pwd_salt uuid NOT NULL,
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL,

  FOREIGN KEY(user_serial_id) 
    REFERENCES users (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

