create table "seller" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  name varchar(64) not null unique,
  seller_id varchar(30) not null unique,

  -- timestamps
  ctime timestamp with time zone not null default current_timestamp,
  mtime timestamp with time zone not null default current_timestamp
);

create table "bill" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  bill_id varchar(30) not null unique,
  remark varchar(256) default null,
  seller_serial_id bigint default null,

  -- timestamps
  ctime timestamp with time zone not null default now(),
  mtime timestamp with time zone not null default now(),

  foreign key(seller_serial_id) 
    references seller (serial_id)
    on update cascade
    on delete cascade
);

create table "payment_method" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  name varchar(64) not null unique,

  -- timestamps
  ctime timestamp with time zone not null default now(),
  mtime timestamp with time zone not null default now()
);

create table "transaction" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  transaction_id varchar(30) not null unique,
  name varchar(128) not null,
  remark varchar(256) default null,
  transaction_time timestamp with time zone not null,
  payment_method_serial_id bigint not null,
  seller_cost numeric(12, 2) not null,
  bill_serial_id bigint default null,

  -- timestamps
  ctime timestamp with time zone not null default now(),
  mtime timestamp with time zone not null default now(),
  
  foreign key(payment_method_serial_id) 
    references payment_method (serial_id)
    on update cascade
    on delete cascade,
  foreign key(bill_serial_id) 
    references bill (serial_id)
    on update cascade
    on delete cascade
);

create table "tag" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  name varchar(64) not null unique,

  -- timestamps
  ctime timestamp with time zone not null default now(),
  mtime timestamp with time zone not null default now()
);

create table "transaction_tag" (
  transaction_serial_id bigint not null,
  tag_serial_id bigint not null,

  primary key (transaction_serial_id, tag_serial_id),
  foreign key(transaction_serial_id)
    references transaction (serial_id)
    on update cascade
    on delete cascade,
  foreign key(tag_serial_id)
    references tag (serial_id)
    on update cascade
    on delete cascade
);

create table "unit_type" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  name varchar(64) not null unique,

  -- timestamps
  ctime timestamp with time zone not null default now(),
  mtime timestamp with time zone not null default now()
);

create table "unit_cost" (
  serial_id bigint generated by default as identity (start with 1) primary key,
  unit_type_serial_id bigint not null,
  cost_per_unit numeric(12, 2) not null,

  unique (unit_type_serial_id, cost_per_unit),
  foreign key(unit_type_serial_id)
    references unit_type (serial_id)
    on update cascade
    on delete cascade
);

create table "transaction_unit" (
  transaction_serial_id bigint primary key,
  unit numeric(10, 3) not null,
  unit_cost_serial_id bigint not null,

  foreign key(unit_cost_serial_id)
    references unit_cost (serial_id)
    on update cascade
    on delete cascade
);

insert into "payment_method" 
    (name, ctime, mtime) values 
    ('Cash', now(), now()),
    ('Upi', now(), now()),
    ('Card', now(), now()),
    ('Unknown', now(), now());

insert into "seller" 
    (name, seller_id) values 
    ('Abc', '0001'),
    ('pqr', '0002'),
    ('hello', '0003'),
    ('bc', '0004');

