CREATE TABLE "payment_method" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW()
);

INSERT INTO "payment_method" 
    (name, ctime, mtime) VALUES 
    ('cash', now(), now()),
    ('upi', now(), now()),
    ('card', now(), now()),
    ('unknown', now(), now());



CREATE TABLE "tag" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "unit_type" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "unit_cost" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  unit_type_serial_id BIGINT NOT NULL,
  cost_per_unit NUMERIC(12, 2) NOT NULL,

  UNIQUE (unit_type_serial_id, cost_per_unit),
  FOREIGN KEY(unit_type_serial_id)
    REFERENCES unit_type (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);


CREATE TABLE "seller" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  seller_id varchar(30) NOT NULL UNIQUE,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "bill" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  bill_id varchar(30) NOT NULL UNIQUE,
  remark VARCHAR(256) DEFAULT NULL,
  seller_serial_id BIGINT DEFAULT NULL,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW(),

  FOREIGN KEY(seller_serial_id) 
    REFERENCES seller (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE "transaction" (
  serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,

  name VARCHAR(128) NOT NULL,
  remark VARCHAR(256) DEFAULT NULL,
  transaction_time TIMESTAMPZ NOT NULL,
  payment_method_serial_id BIGINT NOT NULL,
  seller_cost NUMERIC(12, 2) NOT NULL,
  bill_serial_id BIGINT DEFAULT NULL,

  -- TIMESTAMPs
  ctime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  mtime TIMESTAMPZ NOT NULL DEFAULT NOW(),
  
  FOREIGN KEY(payment_method_serial_id) 
    REFERENCES payment_method (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(bill_serial_id) 
    REFERENCES bill (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE "transaction_tag" (
  transaction_serial_id BIGINT NOT NULL,
  tag_serial_id BIGINT NOT NULL,

  PRIMARY KEY (transaction_serial_id, tag_serial_id),
  FOREIGN KEY(transaction_serial_id)
    REFERENCES transaction (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY(tag_serial_id)
    REFERENCES tag (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE "transaction_unit" (
  transaction_serial_id BIGINT PRIMARY KEY,
  unit NUMERIC(10, 3) NOT NULL,
  unit_cost_serial_id BIGINT NOT NULL,

  FOREIGN KEY(unit_cost_serial_id)
    REFERENCES unit_cost (serial_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

